# Generated by Django 4.0.2 on 2022-03-22 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_apps', '0002_task_project_alter_task_comment_alter_task_text_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='task',
            field=models.ManyToManyField(to='todo_apps.Task'),
        ),
    ]
