# Generated by Django 4.0.2 on 2022-03-05 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_apps', '0002_task_owner_alter_task_text_desc'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='comment',
            field=models.TextField(default='', max_length=10000),
        ),
    ]
