# Generated by Django 4.0.2 on 2022-03-10 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_apps', '0003_task_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='date_due',
            field=models.TextField(default='', max_length=13),
        ),
    ]
