# Generated by Django 4.0.2 on 2022-03-14 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo_apps', '0004_task_date_due'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='task',
            name='date_due',
            field=models.DateField(),
        ),
    ]
